# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: iOS Fastlane

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: macos-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      # List files to ensure the Gemfile is found
      - name: List Files
        run: |
          ls -la
          
      - name: Install Dependencies
        run: |
          brew install libxml2 libxslt
          cd FastlaneSession/
          gem install bundler
          gem install fastlane
          ruby -v
          bundle install --retry=3 --jobs=4
          fastlane run setup_ci force:true
          bundle exec fastlane ios create_new_keychain

      - name: Install App Provisioning
        run: |
          ls -la
          cd FastlaneSession/
          bundle exec fastlane ios app_provisioning

      - name: Build and Archive
        run: |
          cd FastlaneSession/
          bundle exec fastlane ios build_and_archive

      - name: Ship to Firebase
        run: |
          cd FastlaneSession/
          bundle exec fastlane ios distribute_to_firebase
